[package]
name = "liborbital"
version = "0.1.0"
authors = ["Tibor Nagy <xnagytibor@gmail.com>"]
license-file = "LICENSE"
readme = "README.md"

[lib]
name = "orbital"
crate-type = ["staticlib"]

[dependencies]
orbclient = "0.3.13"

[build-dependencies]
cbindgen = "0.6.0"
